### ISSUE TITLE
Error parsing and sending video_id when casting

### ISSUE THREAD

**Issue by jstehn** [erdnaxeli/castblock#52] opened 2022-11-07 19:15 UTC
I am currently casting from a Google Pixel to a Chromecast with Google TV and get this error every time I start a video.

```
2022-11-07T19:05:46.356795Z  DEBUG - castblock.blocker: Youtube video playing -- id: "", current_time: 25.777
2022-11-07T19:05:46.356815Z  DEBUG - http.client: Performing request -- method: "GET", host: "sponsor.ajay.app", port: 443, resource: "/api/skipSegments?categories=%5B%22sponsor%22%2C%22selfpromo%22%5D&videoID="
2022-11-07T19:05:46.489323Z  ERROR - castblock.sponsorblock: Error from Sponsorblock -- status_code: 400, video_id: ""
2022-11-07T19:05:47.888450Z  DEBUG - castblock.blocker: Received message -- application: "Backdrop"
2022-11-07T19:05:48.396786Z  DEBUG - castblock.blocker: Received message -- application: "YouTube"
2022-11-07T19:05:48.396789Z  DEBUG - castblock.blocker: Youtube video playing -- id: "", current_time: 27.818
2022-11-07T19:05:48.396804Z  DEBUG - http.client: Performing request -- method: "GET", host: "sponsor.ajay.app", port: 443, resource: "/api/skipSegments?categories=%5B%22sponsor%22%2C%22selfpromo%22%5D&videoID="
2022-11-07T19:05:48.488795Z  ERROR - castblock.sponsorblock: Error from Sponsorblock -- status_code: 400, video_id: ""
2022-11-07T19:05:49.893342Z  DEBUG - castblock.blocker: Received message -- application: "Backdrop"
2022-11-07T19:05:50.201652Z  DEBUG - castblock.blocker: Checking for new devices
2022-11-07T19:05:50.201660Z  DEBUG - http.client: Performing request -- method: "GET", host: "127.0.0.1", port: 8011, resource: "/devices"
2022-11-07T19:05:50.425737Z  DEBUG - castblock.blocker: Received message -- application: "YouTube"
2022-11-07T19:05:50.425739Z  DEBUG - castblock.blocker: Youtube video playing -- id: "", current_time: 29.846
2022-11-07T19:05:50.425752Z  DEBUG - http.client: Performing request -- method: "GET", host: "sponsor.ajay.app", port: 443, resource: "/api/skipSegments?categories=%5B%22sponsor%22%2C%22selfpromo%22%5D&videoID="
2022-11-07T19:05:50.539005Z  ERROR - castblock.sponsorblock: Error from Sponsorblock -- status_code: 400, video_id: ""
2022-11-07T19:05:51.899283Z  DEBUG - castblock.blocker: Received message -- application: "Backdrop"
2022-11-07T19:05:52.457697Z  DEBUG - castblock.blocker: Received message -- application: "YouTube"
2022-11-07T19:05:52.457700Z  DEBUG - castblock.blocker: Youtube video playing -- id: "", current_time: 31.874
2022-11-07T19:05:52.457715Z  DEBUG - http.client: Performing request -- method: "GET", host: "sponsor.ajay.app", port: 443, resource: "/api/skipSegments?categories=%5B%22sponsor%22%2C%22selfpromo%22%5D&videoID="
2022-11-07T19:05:52.553834Z  ERROR - castblock.sponsorblock: Error from Sponsorblock -- status_code: 400, video_id: ""
2022-11-07T19:05:53.907224Z  DEBUG - castblock.blocker: Received message -- application: "Backdrop"
2022-11-07T19:05:54.526444Z  DEBUG - castblock.chromecast: Unhandled payload: Missing JSON attribute: customData
parsing Castblock::Chromecast::WatchMessagePayload::PayloadStatus at line 1, column 48
parsing Castblock::Chromecast::WatchMessagePayload#status at line 1, column 38
```

**Comment by RemcoSchrijver** [comment] 2022-11-25 20:40
Probably a duplicate of #24

**Comment by erdnaxeli** [comment] 2022-12-09 14:18
It is indeed!

**Closed by erdnaxeli** 2022-12-09 14:18 UTC
