### ISSUE TITLE
Crash if dns fails

### ISSUE THREAD

**Issue by stephen304** [erdnaxeli/castblock#26] opened 2021-09-30 21:50 UTC
I recently did some work on my network and had DNS down for a bit and it looks like it triggered a crash. Looks like dns resolution errors aren't caught. I think just silently failing is fine since it would just try again the next segment.

![Screenshot_20210930_174633](https://user-images.githubusercontent.com/981915/135534715-3501295a-3936-4c87-a80e-f6ea0b24f8cb.png)
![Screenshot_20210930_174651](https://user-images.githubusercontent.com/981915/135534717-9d2402f2-22a7-441b-a894-b9bbfd9f6b32.png)

**Comment by erdnaxeli** [comment] 2021-10-01 15:38
Duplicate of #20

**Closed by erdnaxeli** 2021-10-01 15:38 UTC
Labels: bug
